version: "3"
services:
  api:
    build: .
    depends_on: 
      - postgres
    ports:
      - 8000:8000
      #- <port on localhost>:<port on container>
    # env_file:
    #   -./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234567
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=67yu89koloi9878ko
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=postgres

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

