name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 1234567
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      SECRET_KEY: 67yu89koloi9878ko
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 300
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python Version 3.13.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run:
          pip install pytest
          pytest
        